export const READ_REGIONS_REQUEST = 'READ_REGIONS_REQUEST';
export const READ_REGIONS_FAILURE = 'READ_REGIONS_FAILURE';
export const READ_REGIONS_SUCCESS = 'READ_REGIONS_SUCCESS';
export const SET_CURRENT_REGION = 'SET_CURRENT_REGION';
